# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _VERSION: 'latest'

steps:
  # build base image for python 3.7
  # - name: gcr.io/kaniko-project/executor
  #   id: base-py37
  #   args:
  #     - --dockerfile=Dockerfile.py37
  #     - --destination=gcr.io/dataflow-geobeam/base-py37:$_VERSION
  #     - --cache=true
  #       #
  # build base image for python 3.8+
  #
  - name: gcr.io/kaniko-project/executor
    id: base
    args:
      - --dockerfile=Dockerfile
      - --destination=gcr.io/dataflow-geobeam/base:$_VERSION
      - --cache=true

  # build examples image for Python 3.7
  #- name: gcr.io/kaniko-project/executor
  #  id: example-py37
  #  args:
  #    - --dockerfile=geobeam/examples/Dockerfile.py37
  #    - --destination=gcr.io/dataflow-geobeam/example-py37:$_VERSION
  #    - --cache=true
  #  waitFor: ['base']

   # build examples image for Python 3.8+
  - name: gcr.io/kaniko-project/executor
    id: example
    args:
      - --dockerfile=geobeam/examples/Dockerfile
      - --destination=gcr.io/dataflow-geobeam/example:$_VERSION
      - --cache=true
    waitFor: ['base']

  - name: gcr.io/dataflow-geobeam/base:$_VERSION
    waitFor: ['base']
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install twine
        python setup.py sdist bdist_wheel
        twine check dist/*

  - name: gcr.io/kaniko-project/executor
    id: sphinx_docs_builder
    args:
      - --dockerfile=docs/Dockerfile
      - --destination=gcr.io/dataflow-geobeam/sphinx
      - --cache=true

  - name: gcr.io/dataflow-geobeam/sphinx
    id: make_docs
    entrypoint: bash
    args:
      - -c
      - |
        make latexpdf
        cp build/latex/geobeam.pdf /workspace/docs.pdf

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: publish_docs
    args: ['gsutil', 'cp', '/workspace/docs.pdf', 'gs://geobeam/docs/all.pdf']

  - name: hashicorp/terraform:0.14.5
    id: tf_apply
    entrypoint: 'sh'
    args:
      - -c
      - |
        terraform init
        terraform apply --auto-approve

  - name: gcr.io/dataflow-geobeam/example
    id: test_shapefile
    entrypoint: 'python'
    args: [
      '-m', 'geobeam.examples.shapefile_parcel',
      '--gcs_url', 'gs://geobeam/examples/ghent-parcels-shp.zip',
      '--dataset', 'examples',
      '--table', 'parcel',
      '--runner', 'DirectRunner',
      '--temp_location', 'gs://geobeam-pipeline-tmp/',
      '--project', 'dataflow-geobeam'
    ]
